docs: add api docs
graasp/graasp-apps pull request #27
Opened 2021-12-03 12:59 UTC by pyphilia

This PR contains the documentation to use the apps api for apps developers. 

close #26

2021-12-03 14:57 UTC, Julien-Torrent requested changes

2021-12-03 14:57 UTC, Julien-Torrent commented on docs/guide.md
> +When an app is added as a resource, it is linked to an item. Therefore, two added apps will corredpond to two different items, which leads them to have different item ids, and different app data.
correspond

2021-12-03 14:57 UTC, Julien-Torrent commented on docs/api.md
> +All following requests need an authentication token receive as describe in the [guide](./guide.md).
received as described

2021-12-03 14:57 UTC, Julien-Torrent commented on docs/api.md
> +- returned value: added app data
created

2021-12-03 14:57 UTC, Julien-Torrent commented on docs/api.md
> +- returned value: added app data
created

2021-12-08 18:51 UTC, juancarlosfarah approved these changes
👍

2021-12-09 08:34 UTC, merged